services:
  rabbitmq-js-client:
    image: rabbitmq:4.1.1-management
    container_name: rabbitmq-js-client
    restart: unless-stopped
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./conf/:/etc/rabbitmq/
