services:
  rabbitmq-rhea:
    image: rabbitmq:4.0.9-management
    container_name: rabbitmq-rhea
    restart: unless-stopped
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_PORT: "5672"
    volumes:
      - ./conf/:/etc/rabbitmq/
